server:
  port: 8005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_API_GATEWAY
    username: root
    password: Akki0808

userServiceUrl: http://user-microservice
userServicePath: /users/profile

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level.com.hashkart.apigateway: DEBUG

management.endpoints.web.exposure.include: "*"
