jwt:
  secret: e37fefb4-67f7-11ec-90d6-0242ac120003
  expires-in: 600
  header: Authorization
  issuer: hashkart

server:
  port: 8005

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_API_GATEWAY
    username: root
    password: Akki0808
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

userServiceUrl: user-microservice
productServiceUrl: product-microservice
cartServiceUrl: cart-microservice
couponServiceUrl: coupon-microservice

zuul:
  routes:
    cartService:
      path: /cart/**
      serviceId: ${cartServiceUrl}
      stripPrefix: false
    productService:
      path: /products/**
      url: ${productServiceUrl}
      stripPrefix: false
    userService:
      path: /users/**
      url: ${userServiceUrl}
      stripPrefix: false
    couponService:
      path: /coupon/**
      url: ${couponServiceUrl}
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management.endpoints.web.exposure.include: mappings

logging.level.com.hashkart.apigateway: INFO
