jwt:
  secret: e37fefb4-67f7-11ec-90d6-0242ac120003
  expires-in: 600
  header: Authorization
  issuer: hashkart

server:
  port: 8005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_API_GATEWAY
    username: root
    password: Akki0808

userServiceUrl: http://user-microservice
userServicePath: /users/profile

logging.level.com.hashkart.apigateway: DEBUG

management.endpoints.web.exposure.include: health,info,refresh,mappings
