app:
  discount:
    defaultDiscount: 10
    thresholdQuantity: 2

productServiceUrl: http://product-microservice
productServiceBasePath: /product
productServiceBulkUpdatePath: /products/bulk
couponServiceUrl: http://coupon-microservice
couponServicePath: /coupon

server:
  port: 8003

spring:
  application:
    name: cart-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_CART_SERVICE
    username: root
    password: Akki0808
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management.endpoints.web.exposure.include: mappings

logging.level.com.hashkart.productmicroservice: INFO
