server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_CART_SERVICE
    username: root
    password: Akki0808

logging.level.com.hashkart.apigateway: DEBUG

management.endpoints.web.exposure.include: health,info,refresh,mappings
