server:
  port: 8004

productServiceUrl: http://product-microservice
productServiceBasePath: /products
productServiceBulkUpdatePath: /products/bulk
couponServiceUrl: http://coupon-microservice
couponServicePath: /coupon

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_COUPON_SERVICE
    username: root
    password: Akki0808

logging.level.com.hashkart.apigateway: DEBUG

management.endpoints.web.exposure.include: "*"
