server.port: 8001

cartServiceUrl: http://cart-microservice
cartServicePath: /cart

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_USER_SERVICE
    username: root
    password: Akki0808

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level.com.hashkart.apigateway: DEBUG

management.endpoints.web.exposure.include: "*"
