cartServiceUrl: http://cart-microservice
cartServicePath: /cart

server.port: 8001

spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/HASHKART_USER_SERVICE
    username: root
    password: Akki0808
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

management.endpoints.web.exposure.include: mappings

logging.level.com.hashkart.apigateway: INFO
